// Auto-generated by scripts/build-roc-pdf-field-map.mjs — do not edit.
import type { RocPdfFieldEntry } from "./roc-pdf-types";

export const ROC_PDF_FIELD_MAP_GENERATED_AT = "2026-06-16T22:32:14.406Z";

export const ROC_PDF_FIELD_MAP_ENTRIES: RocPdfFieldEntry[] = [
  {
    "requirementRef": "1.1.1",
    "page": 41,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94786,
      449.94786,
      557.94786,
      665.9399999999999
    ],
    "checkboxY": 255.72,
    "rationale": {
      "x": 77.76,
      "y": 219.08,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.8",
    "page": 22,
    "pageHeight": 612,
    "checkboxes": [
      206.58,
      305.94,
      403.8345,
      496.1145,
      588.06,
      678.1545
    ],
    "checkboxY": 329.28,
    "rationale": {
      "x": 77.76,
      "y": 293.28,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.1.2",
    "page": 42,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94,
      449.94786,
      557.94786,
      665.94786
    ],
    "checkboxY": 438,
    "rationale": {
      "x": 77.76,
      "y": 401.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.2.1",
    "page": 43,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94,
      449.82786000000004,
      557.82786,
      665.82786
    ],
    "checkboxY": 354.96,
    "rationale": {
      "x": 77.76,
      "y": 318.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.2.2",
    "page": 44,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      343.02,
      450.90786,
      557.82786,
      665.82786
    ],
    "checkboxY": 427.92,
    "rationale": {
      "x": 77.76,
      "y": 391.16,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.2.3",
    "page": 46,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      342.9,
      450.78786,
      557.58786,
      665.82786
    ],
    "checkboxY": 439.56,
    "rationale": {
      "x": 77.76,
      "y": 402.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.2.4",
    "page": 47,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      342.90786,
      450.78786,
      557.58786,
      665.82786
    ],
    "checkboxY": 414.24,
    "rationale": {
      "x": 77.76,
      "y": 377.48,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.2.5",
    "page": 48,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      341.7,
      449.58786000000003,
      557.58786,
      665.82786
    ],
    "checkboxY": 434.28,
    "rationale": {
      "x": 77.76,
      "y": 397.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.2.6",
    "page": 49,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      341.7,
      449.58786000000003,
      557.58786,
      665.82786
    ],
    "checkboxY": 422.52,
    "rationale": {
      "x": 77.76,
      "y": 385.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.2.7",
    "page": 50,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      341.7,
      449.58786000000003,
      557.58786,
      665.82786
    ],
    "checkboxY": 438.6,
    "rationale": {
      "x": 77.76,
      "y": 401.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.2.8",
    "page": 51,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      341.7,
      449.58786000000003,
      557.58786,
      665.82786
    ],
    "checkboxY": 409.44,
    "rationale": {
      "x": 77.76,
      "y": 372.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.3.1",
    "page": 52,
    "pageHeight": 612,
    "checkboxes": [
      125.82786,
      233.70785999999998,
      341.46,
      449.34786,
      557.1078600000001,
      665.46786
    ],
    "checkboxY": 367.68,
    "rationale": {
      "x": 77.76,
      "y": 331.04,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.3.2",
    "page": 53,
    "pageHeight": 612,
    "checkboxes": [
      125.82786,
      233.70785999999998,
      341.46,
      449.34786,
      557.1078600000001,
      665.46786
    ],
    "checkboxY": 409.44,
    "rationale": {
      "x": 77.76,
      "y": 372.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.3.3",
    "page": 54,
    "pageHeight": 612,
    "checkboxes": [
      125.82786,
      233.70785999999998,
      341.46786000000003,
      449.34786,
      557.1078600000001,
      665.46786
    ],
    "checkboxY": 410.76,
    "rationale": {
      "x": 77.76,
      "y": 374,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.4.1",
    "page": 55,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94786,
      449.82786000000004,
      557.82786,
      665.70786
    ],
    "checkboxY": 388.44,
    "rationale": {
      "x": 77.76,
      "y": 351.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.4.2",
    "page": 56,
    "pageHeight": 612,
    "checkboxes": [
      125.94000000000001,
      233.94786,
      341.94,
      449.82786000000004,
      557.82786,
      665.70786
    ],
    "checkboxY": 400.2,
    "rationale": {
      "x": 77.76,
      "y": 363.08,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.4.3",
    "page": 57,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94786,
      449.82786000000004,
      557.82786,
      665.70786
    ],
    "checkboxY": 438.72,
    "rationale": {
      "x": 77.76,
      "y": 402.08,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.4.4",
    "page": 58,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.82786000000004,
      449.82786000000004,
      557.82786,
      665.70786
    ],
    "checkboxY": 439.56,
    "rationale": {
      "x": 77.76,
      "y": 402.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.4.5",
    "page": 59,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.82786000000004,
      449.82,
      557.82786,
      665.70786
    ],
    "checkboxY": 439.2,
    "rationale": {
      "x": 77.76,
      "y": 402.56,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "1.5.1",
    "page": 60,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.82786000000004,
      449.82786000000004,
      557.82786,
      665.70786
    ],
    "checkboxY": 334.2,
    "rationale": {
      "x": 77.76,
      "y": 297.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.1.1",
    "page": 62,
    "pageHeight": 612,
    "checkboxes": [
      125.94000000000001,
      233.82786,
      341.94786,
      449.94786,
      557.82786,
      665.70786
    ],
    "checkboxY": 315.24,
    "rationale": {
      "x": 77.76,
      "y": 278.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.1.2",
    "page": 63,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      341.94786,
      449.94786,
      557.82786,
      665.70786
    ],
    "checkboxY": 430.92,
    "rationale": {
      "x": 77.76,
      "y": 394.16,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.2.1",
    "page": 64,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94786,
      449.94786,
      557.94786,
      665.94786
    ],
    "checkboxY": 314.28,
    "rationale": {
      "x": 77.76,
      "y": 277.52,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.2.2",
    "page": 65,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94786,
      449.94786,
      557.94786,
      665.94786
    ],
    "checkboxY": 170.4,
    "rationale": {
      "x": 77.76,
      "y": 133.76,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.2.3",
    "page": 67,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94,
      449.94786,
      557.94786,
      665.94786
    ],
    "checkboxY": 356.76,
    "rationale": {
      "x": 77.76,
      "y": 320.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.2.4",
    "page": 69,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94786,
      449.94786,
      557.94786,
      665.94786
    ],
    "checkboxY": 431.64,
    "rationale": {
      "x": 77.76,
      "y": 395,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.2.5",
    "page": 70,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94786,
      449.94786,
      557.94786,
      665.94786
    ],
    "checkboxY": 385.68,
    "rationale": {
      "x": 77.76,
      "y": 348.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.2.6",
    "page": 71,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94786,
      449.94786,
      557.94786,
      665.94786
    ],
    "checkboxY": 434.76,
    "rationale": {
      "x": 77.76,
      "y": 398.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.2.7",
    "page": 72,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94,
      341.94786,
      449.94786,
      557.94786,
      665.94786
    ],
    "checkboxY": 434.76,
    "rationale": {
      "x": 77.76,
      "y": 398.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.3.1",
    "page": 74,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      341.82786000000004,
      449.82786000000004,
      557.70786,
      665.58786
    ],
    "checkboxY": 329.64,
    "rationale": {
      "x": 77.76,
      "y": 293,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "2.3.2",
    "page": 76,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      341.82786000000004,
      449.82786000000004,
      557.70786,
      665.70786
    ],
    "checkboxY": 411.48,
    "rationale": {
      "x": 77.76,
      "y": 374.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.1.1",
    "page": 77,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      341.82786000000004,
      449.70786000000004,
      557.70786,
      665.58786
    ],
    "checkboxY": 279.84,
    "rationale": {
      "x": 77.76,
      "y": 243.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.1.2",
    "page": 78,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      341.82786000000004,
      449.70786000000004,
      557.70786,
      665.58786
    ],
    "checkboxY": 437.88,
    "rationale": {
      "x": 77.76,
      "y": 401.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.2.1",
    "page": 79,
    "pageHeight": 612,
    "checkboxes": [
      126.06786000000001,
      233.94786,
      339.42786,
      447.30786,
      557.58786,
      665.70786
    ],
    "checkboxY": 279.24,
    "rationale": {
      "x": 77.76,
      "y": 242.48000000000002,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.3.1",
    "page": 81,
    "pageHeight": 612,
    "checkboxes": [
      125.94000000000001,
      233.70785999999998,
      342.78786,
      450.66786,
      557.34786
    ],
    "checkboxY": 386.04,
    "rationale": {
      "x": 77.76,
      "y": 348.32,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.3.1.1",
    "page": 82,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.70785999999998,
      342.78786,
      450.66786,
      557.34786
    ],
    "checkboxY": 415.2,
    "rationale": {
      "x": 77.76,
      "y": 378.56,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.3.1.2",
    "page": 83,
    "pageHeight": 612,
    "checkboxes": [
      125.46786,
      232.62786,
      339.66786,
      446.46786000000003,
      553.38786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.3.1.3",
    "page": 83,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.70786000000004,
      449.58786000000003,
      557.46786
    ],
    "checkboxY": 177.84,
    "rationale": {
      "x": 77.76,
      "y": 141.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.3.2",
    "page": 84,
    "pageHeight": 612,
    "checkboxes": [
      125.58786,
      232.73999999999998,
      343.26786000000004,
      450.06786,
      553.38786
    ],
    "checkboxY": 326.64,
    "rationale": {
      "x": 77.76,
      "y": 289.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.3.3",
    "page": 85,
    "pageHeight": 612,
    "checkboxes": [
      125.58786,
      232.74786,
      343.26786000000004,
      450.06786,
      553.38786,
      663.30786
    ],
    "checkboxY": 394.8,
    "rationale": {
      "x": 77.76,
      "y": 358.16,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.4.1",
    "page": 86,
    "pageHeight": 612,
    "checkboxes": [
      125.58786,
      232.74786,
      343.26786000000004,
      450.06,
      553.38786,
      663.30786
    ],
    "checkboxY": 386.16,
    "rationale": {
      "x": 77.76,
      "y": 349.4,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.4.2",
    "page": 88,
    "pageHeight": 612,
    "checkboxes": [
      125.58786,
      232.86785999999998,
      343.38786000000005,
      450.06,
      553.38786,
      663.42786
    ],
    "checkboxY": 415.2,
    "rationale": {
      "x": 77.76,
      "y": 378.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.5.1",
    "page": 89,
    "pageHeight": 612,
    "checkboxes": [
      130.38786,
      236.70785999999998,
      342.90786,
      448.50786,
      554.34786,
      663.78786
    ],
    "checkboxY": 113.52,
    "rationale": {
      "x": 126.72,
      "y": 77.52,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.5.1.1",
    "page": 91,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.70785999999998,
      342.90786,
      448.50786,
      554.34786,
      663.78786
    ],
    "checkboxY": 404.16,
    "rationale": {
      "x": 77.76,
      "y": 367.4,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.5.1.2",
    "page": 92,
    "pageHeight": 612,
    "checkboxes": [
      125.70786000000001,
      232.98785999999998,
      343.50786,
      450.06786,
      553.50786,
      663.42786
    ],
    "checkboxY": 233.64,
    "rationale": {
      "x": 77.76,
      "y": 197,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.5.1.3",
    "page": 94,
    "pageHeight": 612,
    "checkboxes": [
      125.70786000000001,
      232.98785999999998,
      338.70786000000004,
      445.50786,
      553.50786,
      663.42786
    ],
    "checkboxY": 395.04,
    "rationale": {
      "x": 77.76,
      "y": 358.28,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.6.1",
    "page": 95,
    "pageHeight": 612,
    "checkboxes": [
      125.70786000000001,
      232.98785999999998,
      338.70786000000004,
      445.50786,
      553.50786,
      663.42786
    ],
    "checkboxY": 337.92,
    "rationale": {
      "x": 77.76,
      "y": 298.04,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.6.1.1",
    "page": 96,
    "pageHeight": 612,
    "checkboxes": [
      129.90786,
      240.78786,
      344.70786000000004,
      449.22786,
      555.54786,
      664.14786
    ],
    "checkboxY": 362.4,
    "rationale": {
      "x": 77.76,
      "y": 325.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.6.1.2",
    "page": 97,
    "pageHeight": 612,
    "checkboxes": [
      129.90786,
      240.78786,
      344.70786000000004,
      449.22786,
      555.54786,
      664.14786
    ],
    "checkboxY": 395.64,
    "rationale": {
      "x": 77.76,
      "y": 359,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.6.1.3",
    "page": 99,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.82786,
      343.02786000000003,
      448.50786,
      554.46786,
      663.78786
    ],
    "checkboxY": 437.88,
    "rationale": {
      "x": 77.76,
      "y": 401.24,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.6.1.4",
    "page": 100,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.82786,
      343.02786000000003,
      448.50786,
      554.46786,
      663.78786
    ],
    "checkboxY": 440.64,
    "rationale": {
      "x": 77.76,
      "y": 403.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.7.1",
    "page": 101,
    "pageHeight": 612,
    "checkboxes": [
      129.90786,
      240.66786,
      344.82786000000004,
      449.34,
      555.66786,
      664.14786
    ],
    "checkboxY": 383.76,
    "rationale": {
      "x": 77.76,
      "y": 347,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.7.2",
    "page": 102,
    "pageHeight": 612,
    "checkboxes": [
      129.90786,
      240.66786,
      344.82786000000004,
      449.34786,
      555.66786,
      664.14786
    ],
    "checkboxY": 433.44,
    "rationale": {
      "x": 77.76,
      "y": 396.68,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.7.3",
    "page": 103,
    "pageHeight": 612,
    "checkboxes": [
      132.06,
      244.62786,
      347.46786000000003,
      447.42,
      553.14786,
      664.50786
    ],
    "checkboxY": 440.76,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.7.4",
    "page": 104,
    "pageHeight": 612,
    "checkboxes": [
      132.06786,
      244.62786,
      347.46786000000003,
      447.42,
      553.14786,
      664.50786
    ],
    "checkboxY": 399.84,
    "rationale": {
      "x": 77.76,
      "y": 363.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.7.5",
    "page": 106,
    "pageHeight": 612,
    "checkboxes": [
      132.06786,
      244.62786,
      347.46786000000003,
      447.42,
      553.14786,
      664.50786
    ],
    "checkboxY": 362.16,
    "rationale": {
      "x": 77.76,
      "y": 325.4,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.7.6",
    "page": 107,
    "pageHeight": 612,
    "checkboxes": [
      127.38786,
      235.50786,
      339.66786,
      444.18,
      550.38786,
      661.50786
    ],
    "checkboxY": 423.6,
    "rationale": {
      "x": 77.76,
      "y": 386.96,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.7.7",
    "page": 108,
    "pageHeight": 612,
    "checkboxes": [
      132.18786,
      239.46786,
      344.94786,
      448.38,
      551.58786,
      661.9878600000001
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 83.16,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.7.8",
    "page": 109,
    "pageHeight": 612,
    "checkboxes": [
      129.54786,
      239.46786,
      344.94786,
      447.65999999999997,
      553.38786,
      664.62786
    ],
    "checkboxY": 428.64,
    "rationale": {
      "x": 77.76,
      "y": 391.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "3.7.9",
    "page": 110,
    "pageHeight": 612,
    "checkboxes": [
      127.38786,
      235.50786,
      339.66786,
      444.18,
      550.38786,
      661.50786
    ],
    "checkboxY": 428.16,
    "rationale": {
      "x": 77.76,
      "y": 391.52,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "4.1.1",
    "page": 111,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      235.98785999999998,
      343.98786,
      447.42,
      551.46786,
      661.8678600000001
    ],
    "checkboxY": 288.84,
    "rationale": {
      "x": 77.76,
      "y": 252.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "4.1.2",
    "page": 112,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      235.98785999999998,
      343.98,
      447.42,
      551.46786,
      661.8678600000001
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "4.2.1",
    "page": 113,
    "pageHeight": 612,
    "checkboxes": [
      127.38786,
      235.50786,
      342.18786,
      446.7,
      550.38786,
      663.66786
    ],
    "checkboxY": 318.72,
    "rationale": {
      "x": 77.76,
      "y": 282.08,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "4.2.1.1",
    "page": 114,
    "pageHeight": 612,
    "checkboxes": [
      127.50786000000001,
      235.74786,
      342.30786,
      446.7,
      550.38786,
      663.78786
    ],
    "checkboxY": 206.88,
    "rationale": {
      "x": 77.76,
      "y": 167,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "4.2.1.2",
    "page": 115,
    "pageHeight": 612,
    "checkboxes": [
      127.50786000000001,
      235.74786,
      342.30786,
      446.7,
      550.38786,
      663.66786
    ],
    "checkboxY": 267.96,
    "rationale": {
      "x": 77.76,
      "y": 231.32,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "4.2.2",
    "page": 116,
    "pageHeight": 612,
    "checkboxes": [
      127.38786,
      235.62786,
      342.30786,
      446.7,
      550.38786,
      663.78786
    ],
    "checkboxY": 420,
    "rationale": {
      "x": 77.76,
      "y": 383.24,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.1.1",
    "page": 117,
    "pageHeight": 612,
    "checkboxes": [
      131.34786,
      237.42785999999998,
      340.14786000000004,
      439.86,
      543.06786,
      660.78786
    ],
    "checkboxY": 282.36,
    "rationale": {
      "x": 82.92,
      "y": 245.72000000000003,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.1.2",
    "page": 118,
    "pageHeight": 612,
    "checkboxes": [
      128.70786,
      237.66786,
      340.38786000000005,
      440.58,
      545.46786,
      662.46786
    ],
    "checkboxY": 436.68,
    "rationale": {
      "x": 77.76,
      "y": 400.04,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.2.1",
    "page": 119,
    "pageHeight": 612,
    "checkboxes": [
      133.14785999999998,
      240.66786,
      342.90786,
      440.82,
      545.1078600000001,
      658.50786
    ],
    "checkboxY": 380.28,
    "rationale": {
      "x": 82.92,
      "y": 343.52,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.2.2",
    "page": 120,
    "pageHeight": 612,
    "checkboxes": [
      133.14785999999998,
      240.66786,
      342.90786,
      440.82,
      545.1078600000001,
      658.50786
    ],
    "checkboxY": 412.44,
    "rationale": {
      "x": 82.92,
      "y": 375.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.2.3",
    "page": 121,
    "pageHeight": 612,
    "checkboxes": [
      131.10786,
      236.82786,
      341.10786,
      440.82,
      544.62786,
      658.26786
    ],
    "checkboxY": 398.16,
    "rationale": {
      "x": 82.92,
      "y": 361.4,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.2.3.1",
    "page": 123,
    "pageHeight": 612,
    "checkboxes": [
      128.46786,
      237.18786,
      341.34786,
      440.09999999999997,
      543.42786,
      657.78786
    ],
    "checkboxY": 415.68,
    "rationale": {
      "x": 77.76,
      "y": 379.04,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.3.1",
    "page": 124,
    "pageHeight": 612,
    "checkboxes": [
      130.14786,
      240.30785999999998,
      342.90786,
      442.86,
      545.70786,
      659.46786
    ],
    "checkboxY": 391.2,
    "rationale": {
      "x": 77.76,
      "y": 354.56,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.3.2",
    "page": 125,
    "pageHeight": 612,
    "checkboxes": [
      130.14786,
      240.30785999999998,
      342.90786,
      442.14,
      546.66786,
      658.7478600000001
    ],
    "checkboxY": 398.16,
    "rationale": {
      "x": 77.76,
      "y": 361.4,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.3.2.1",
    "page": 127,
    "pageHeight": 612,
    "checkboxes": [
      130.14,
      239.94786,
      342.42786,
      441.42,
      545.58786,
      658.26786
    ],
    "checkboxY": 416.28,
    "rationale": {
      "x": 77.76,
      "y": 379.04,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.3.3",
    "page": 128,
    "pageHeight": 612,
    "checkboxes": [
      130.14786,
      240.30785999999998,
      342.90786,
      440.82,
      544.62786,
      657.90786
    ],
    "checkboxY": 384,
    "rationale": {
      "x": 77.76,
      "y": 347.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.3.4",
    "page": 129,
    "pageHeight": 612,
    "checkboxes": [
      126.78786000000001,
      233.94786,
      341.10786,
      442.98,
      547.02786,
      661.62786
    ],
    "checkboxY": 322.08,
    "rationale": {
      "x": 77.76,
      "y": 285.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.3.5",
    "page": 130,
    "pageHeight": 612,
    "checkboxes": [
      127.02786,
      234.66786,
      339.42786,
      442.86,
      547.14786,
      657.42786
    ],
    "checkboxY": 430.2,
    "rationale": {
      "x": 77.76,
      "y": 393.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "5.4.1",
    "page": 131,
    "pageHeight": 612,
    "checkboxes": [
      127.50786000000001,
      235.86785999999998,
      339.90786,
      444.18,
      550.26786,
      661.50786
    ],
    "checkboxY": 382.44,
    "rationale": {
      "x": 77.76,
      "y": 345.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.1.1",
    "page": 132,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      235.98785999999998,
      339.90786,
      444.18,
      550.38786,
      661.50786
    ],
    "checkboxY": 317.28,
    "rationale": {
      "x": 77.76,
      "y": 280.52,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.1.2",
    "page": 133,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      236.10786,
      340.02786000000003,
      440.58,
      546.66786,
      661.38786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.2.1",
    "page": 134,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      236.10786,
      340.02786000000003,
      440.58,
      546.66786,
      661.38786
    ],
    "checkboxY": 354.72,
    "rationale": {
      "x": 77.76,
      "y": 317.96,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.2.2",
    "page": 135,
    "pageHeight": 612,
    "checkboxes": [
      133.86785999999998,
      242.10786,
      342.42786,
      442.74,
      550.02786,
      662.58786
    ],
    "checkboxY": 397.32,
    "rationale": {
      "x": 83.04,
      "y": 360.68,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.2.3",
    "page": 136,
    "pageHeight": 612,
    "checkboxes": [
      133.86785999999998,
      242.10786,
      342.42786,
      442.02,
      549.30786,
      662.58786
    ],
    "checkboxY": 387,
    "rationale": {
      "x": 83.04,
      "y": 350.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.2.3.1",
    "page": 137,
    "pageHeight": 612,
    "checkboxes": [
      131.82786,
      238.26785999999998,
      340.74786,
      441.3,
      548.22786,
      662.34786
    ],
    "checkboxY": 412.44,
    "rationale": {
      "x": 83.04,
      "y": 375.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.2.4",
    "page": 138,
    "pageHeight": 612,
    "checkboxes": [
      129.18786,
      238.62786,
      341.10786,
      440.58,
      547.14786,
      661.8678600000001
    ],
    "checkboxY": 300.72,
    "rationale": {
      "x": 77.76,
      "y": 263.96,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.3.1",
    "page": 139,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      235.98785999999998,
      340.14786000000004,
      440.58,
      546.42786,
      661.26786
    ],
    "checkboxY": 310.92,
    "rationale": {
      "x": 82.2,
      "y": 274.16,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.3.2",
    "page": 141,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      240.06786,
      341.82786000000004,
      441.3,
      547.8678600000001,
      661.9878600000001
    ],
    "checkboxY": 415.2,
    "rationale": {
      "x": 77.76,
      "y": 378.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.3.3",
    "page": 142,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      240.06786,
      341.82786000000004,
      440.58,
      547.14786,
      661.9878600000001
    ],
    "checkboxY": 400.32,
    "rationale": {
      "x": 77.76,
      "y": 363.56,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.4.1",
    "page": 143,
    "pageHeight": 612,
    "checkboxes": [
      134.46786,
      243.78786,
      341.46786000000003,
      439.98,
      548.82786,
      662.22786
    ],
    "checkboxY": 188.76,
    "rationale": {
      "x": 83.04,
      "y": 152,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.4.2",
    "page": 145,
    "pageHeight": 612,
    "checkboxes": [
      134.46786,
      243.78786,
      341.46786000000003,
      439.26,
      548.1078600000001,
      662.22786
    ],
    "checkboxY": 347.76,
    "rationale": {
      "x": 83.04,
      "y": 311.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.4.3",
    "page": 146,
    "pageHeight": 612,
    "checkboxes": [
      127.02786,
      234.54786,
      337.02786000000003,
      438.42,
      546.90786,
      661.7478600000001
    ],
    "checkboxY": 384,
    "rationale": {
      "x": 77.76,
      "y": 347.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.5.1",
    "page": 148,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      235.98785999999998,
      340.14786000000004,
      440.58,
      546.18786,
      661.26786
    ],
    "checkboxY": 312.72,
    "rationale": {
      "x": 77.76,
      "y": 276.08,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.5.2",
    "page": 150,
    "pageHeight": 612,
    "checkboxes": [
      134.70785999999998,
      244.02786,
      341.70786000000004,
      440.21999999999997,
      549.30786,
      662.46786
    ],
    "checkboxY": 423.36,
    "rationale": {
      "x": 83.16,
      "y": 386.72,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.5.3",
    "page": 151,
    "pageHeight": 612,
    "checkboxes": [
      134.70785999999998,
      244.02786,
      341.70786000000004,
      439.38,
      548.46786,
      662.46786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 83.16,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.5.4",
    "page": 152,
    "pageHeight": 612,
    "checkboxes": [
      129.3,
      234.78786,
      337.02786000000003,
      438.53999999999996,
      547.14786,
      661.8678600000001
    ],
    "checkboxY": 429.72,
    "rationale": {
      "x": 82.2,
      "y": 392.6,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.5.5",
    "page": 153,
    "pageHeight": 612,
    "checkboxes": [
      131.82786,
      238.38786,
      339.30786,
      437.94,
      543.54786,
      659.58786
    ],
    "checkboxY": 428.16,
    "rationale": {
      "x": 83.04,
      "y": 391.52,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "6.5.6",
    "page": 155,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      239.94786,
      341.70786000000004,
      440.58,
      547.14786,
      661.8678600000001
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.1.1",
    "page": 156,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      235.98785999999998,
      339.90786,
      440.46,
      546.66786,
      661.38786
    ],
    "checkboxY": 273,
    "rationale": {
      "x": 77.76,
      "y": 236.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.1.2",
    "page": 157,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      236.10786,
      339.90786,
      440.58,
      546.66786,
      661.50786
    ],
    "checkboxY": 420,
    "rationale": {
      "x": 77.76,
      "y": 383.24,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.2.1",
    "page": 158,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      236.10786,
      339.90786,
      440.58,
      546.66786,
      661.50786
    ],
    "checkboxY": 357.48,
    "rationale": {
      "x": 77.76,
      "y": 320.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.2.2",
    "page": 159,
    "pageHeight": 612,
    "checkboxes": [
      131.82,
      243.78786,
      343.50786,
      442.02,
      548.94786,
      662.22786
    ],
    "checkboxY": 412.92,
    "rationale": {
      "x": 77.76,
      "y": 375.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.2.3",
    "page": 160,
    "pageHeight": 612,
    "checkboxes": [
      131.82786,
      243.78786,
      343.50786,
      441.42,
      548.34786,
      662.22786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.2.4",
    "page": 161,
    "pageHeight": 612,
    "checkboxes": [
      127.02786,
      234.54786,
      339.06786,
      440.58,
      547.14786,
      661.8678600000001
    ],
    "checkboxY": 369.96,
    "rationale": {
      "x": 77.76,
      "y": 333.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.2.5",
    "page": 163,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.22786,
      340.02786000000003,
      440.58,
      546.66786,
      661.50786
    ],
    "checkboxY": 392.76,
    "rationale": {
      "x": 77.76,
      "y": 356.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.2.5.1",
    "page": 164,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      236.10786,
      340.02786000000003,
      440.46,
      546.54786,
      661.26786
    ],
    "checkboxY": 369.96,
    "rationale": {
      "x": 77.76,
      "y": 333.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.2.6",
    "page": 166,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.22786,
      340.02786000000003,
      440.58,
      546.66786,
      661.50786
    ],
    "checkboxY": 412.44,
    "rationale": {
      "x": 77.76,
      "y": 375.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.3.1",
    "page": 167,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.22786,
      340.02786000000003,
      440.7,
      546.78786,
      661.50786
    ],
    "checkboxY": 396.96,
    "rationale": {
      "x": 77.76,
      "y": 360.32,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.3.2",
    "page": 168,
    "pageHeight": 612,
    "checkboxes": [
      132.42785999999998,
      239.94786,
      341.70786000000004,
      441.3,
      547.7478600000001,
      661.8678600000001
    ],
    "checkboxY": 429.48,
    "rationale": {
      "x": 83.04,
      "y": 392.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "7.3.3",
    "page": 169,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      239.94786,
      341.70786000000004,
      440.58,
      547.14786,
      661.8678600000001
    ],
    "checkboxY": 438.12,
    "rationale": {
      "x": 77.76,
      "y": 401.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.1.1",
    "page": 170,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      236.10786,
      340.02786000000003,
      440.58,
      546.66786,
      661.38786
    ],
    "checkboxY": 317.28,
    "rationale": {
      "x": 77.76,
      "y": 280.52,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.1.2",
    "page": 171,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.22786,
      340.02786000000003,
      440.58,
      546.66786,
      661.50786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.2.1",
    "page": 172,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      236.10786,
      340.02786000000003,
      440.58,
      546.66786,
      661.38786
    ],
    "checkboxY": 396.96,
    "rationale": {
      "x": 77.76,
      "y": 360.32,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.2.2",
    "page": 173,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      239.94786,
      341.70786000000004,
      441.3,
      547.8678600000001,
      661.9878600000001
    ],
    "checkboxY": 345,
    "rationale": {
      "x": 77.76,
      "y": 308.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.2.3",
    "page": 175,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      239.94786,
      341.70786000000004,
      440.58,
      547.14786,
      661.9878600000001
    ],
    "checkboxY": 429.24,
    "rationale": {
      "x": 77.76,
      "y": 392.6,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.2.4",
    "page": 176,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      239.94,
      341.70786000000004,
      441.3,
      547.8678600000001,
      661.9878600000001
    ],
    "checkboxY": 411.84,
    "rationale": {
      "x": 77.76,
      "y": 375.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.2.5",
    "page": 177,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      239.94786,
      341.70786000000004,
      440.58,
      547.14786,
      661.9878600000001
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.2.6",
    "page": 178,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      239.94786,
      341.70786000000004,
      441.3,
      547.8678600000001,
      661.9878600000001
    ],
    "checkboxY": 439.68,
    "rationale": {
      "x": 77.76,
      "y": 402.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.2.7",
    "page": 179,
    "pageHeight": 612,
    "checkboxes": [
      129.78786,
      239.94786,
      341.70786000000004,
      440.58,
      547.14786,
      661.9878600000001
    ],
    "checkboxY": 412.08,
    "rationale": {
      "x": 77.76,
      "y": 375.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.2.8",
    "page": 180,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.22786,
      340.02786000000003,
      444.3,
      550.50786,
      661.38786
    ],
    "checkboxY": 431.88,
    "rationale": {
      "x": 77.76,
      "y": 395.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.1",
    "page": 181,
    "pageHeight": 612,
    "checkboxes": [
      131.82786,
      243.78786,
      345.54786,
      444.06,
      548.94786,
      662.34786
    ],
    "checkboxY": 354.72,
    "rationale": {
      "x": 77.76,
      "y": 317.96,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.2",
    "page": 182,
    "pageHeight": 612,
    "checkboxes": [
      131.82786,
      243.78786,
      345.54786,
      443.46,
      548.34786,
      662.34786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.3",
    "page": 183,
    "pageHeight": 612,
    "checkboxes": [
      127.02000000000001,
      234.54786,
      340.26786000000004,
      441.9,
      547.14786,
      661.9878600000001
    ],
    "checkboxY": 440.76,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.4",
    "page": 184,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.22786,
      340.02786000000003,
      440.46,
      546.66786,
      661.50786
    ],
    "checkboxY": 412.08,
    "rationale": {
      "x": 77.76,
      "y": 375.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.5",
    "page": 185,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.22786,
      340.86786,
      441.42,
      546.66786,
      661.50786
    ],
    "checkboxY": 411.6,
    "rationale": {
      "x": 77.76,
      "y": 374.96,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.6",
    "page": 186,
    "pageHeight": 612,
    "checkboxes": [
      132.54786,
      240.30785999999998,
      344.10786,
      443.7,
      547.9878600000001,
      661.8678600000001
    ],
    "checkboxY": 387,
    "rationale": {
      "x": 83.04,
      "y": 350.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.7",
    "page": 187,
    "pageHeight": 612,
    "checkboxes": [
      129.90786,
      240.30785999999998,
      343.14786000000004,
      441.9,
      547.14786,
      661.8678600000001
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.8",
    "page": 188,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.22786,
      340.86786,
      441.3,
      546.66786,
      661.5
    ],
    "checkboxY": 372.96,
    "rationale": {
      "x": 77.76,
      "y": 336.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.9",
    "page": 189,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.22786,
      340.86786,
      441.42,
      546.54786,
      661.38786
    ],
    "checkboxY": 316.56,
    "rationale": {
      "x": 77.76,
      "y": 279.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.10",
    "page": 190,
    "pageHeight": 612,
    "checkboxes": [
      127.74786,
      236.22786,
      336.42786,
      436.98,
      546.66786,
      661.50786
    ],
    "checkboxY": 387,
    "rationale": {
      "x": 77.76,
      "y": 350.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.10.1",
    "page": 191,
    "pageHeight": 612,
    "checkboxes": [
      132.66786,
      240.54786,
      344.46786000000003,
      443.94,
      548.1078600000001,
      662.1078600000001
    ],
    "checkboxY": 361.8,
    "rationale": {
      "x": 83.16,
      "y": 325.16,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.3.11",
    "page": 192,
    "pageHeight": 612,
    "checkboxes": [
      130.02786,
      240.54786,
      344.46786000000003,
      442.98,
      547.26786,
      662.1078600000001
    ],
    "checkboxY": 412.44,
    "rationale": {
      "x": 77.76,
      "y": 375.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.4.1",
    "page": 194,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      236.10786,
      340.02786000000003,
      440.58,
      546.66786,
      661.38786
    ],
    "checkboxY": 394.92,
    "rationale": {
      "x": 77.76,
      "y": 358.16,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.4.2",
    "page": 195,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      236.10786,
      342.54786,
      443.09999999999997,
      546.66786,
      661.50786
    ],
    "checkboxY": 426.48,
    "rationale": {
      "x": 77.76,
      "y": 389.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.4.3",
    "page": 196,
    "pageHeight": 612,
    "checkboxes": [
      125.70786000000001,
      233.46786,
      341.22786,
      448.98786,
      556.8678600000001,
      665.34786
    ],
    "checkboxY": 426.6,
    "rationale": {
      "x": 77.76,
      "y": 389.96,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.5.1",
    "page": 197,
    "pageHeight": 612,
    "checkboxes": [
      127.62786,
      236.10786,
      339.90786,
      440.58,
      546.54786,
      661.38786
    ],
    "checkboxY": 315.48,
    "rationale": {
      "x": 77.76,
      "y": 278.72,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.6.1",
    "page": 199,
    "pageHeight": 612,
    "checkboxes": [
      134.46786,
      244.02786,
      343.62786,
      442.14,
      549.30786,
      662.46786
    ],
    "checkboxY": 298.2,
    "rationale": {
      "x": 82.92,
      "y": 261.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.6.2",
    "page": 200,
    "pageHeight": 612,
    "checkboxes": [
      134.46786,
      244.02786,
      343.62786,
      441.53999999999996,
      548.58786,
      662.46786
    ],
    "checkboxY": 408,
    "rationale": {
      "x": 82.92,
      "y": 371.24,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "8.6.3",
    "page": 201,
    "pageHeight": 612,
    "checkboxes": [
      127.14786000000001,
      234.89999999999998,
      339.18786,
      440.58,
      547.26786,
      662.1078600000001
    ],
    "checkboxY": 380.04,
    "rationale": {
      "x": 77.76,
      "y": 343.4,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.1.1",
    "page": 203,
    "pageHeight": 612,
    "checkboxes": [
      132.06786,
      238.86785999999998,
      341.10786,
      441.3,
      548.46786,
      662.46786
    ],
    "checkboxY": 316.44,
    "rationale": {
      "x": 83.16,
      "y": 279.68,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.1.2",
    "page": 204,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.86785999999998,
      341.10786,
      441.3,
      548.46786,
      662.46786
    ],
    "checkboxY": 439.32,
    "rationale": {
      "x": 77.76,
      "y": 402.68,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.2.1",
    "page": 205,
    "pageHeight": 612,
    "checkboxes": [
      127.26786,
      235.14785999999998,
      339.42786,
      440.7,
      547.38786,
      662.22786
    ],
    "checkboxY": 391.08,
    "rationale": {
      "x": 77.76,
      "y": 354.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.2.1.1",
    "page": 206,
    "pageHeight": 612,
    "checkboxes": [
      127.26786,
      235.14785999999998,
      339.30786,
      440.7,
      547.38786,
      662.22786
    ],
    "checkboxY": 372.96,
    "rationale": {
      "x": 77.76,
      "y": 336.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.2.2",
    "page": 208,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.86785999999998,
      340.98786,
      441.3,
      548.34786,
      662.58786
    ],
    "checkboxY": 438.96,
    "rationale": {
      "x": 77.76,
      "y": 402.32,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.2.3",
    "page": 209,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.86785999999998,
      340.98786,
      441.3,
      548.34786,
      662.58786
    ],
    "checkboxY": 435.6,
    "rationale": {
      "x": 77.76,
      "y": 398.96,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.2.4",
    "page": 210,
    "pageHeight": 612,
    "checkboxes": [
      127.26786,
      235.02786,
      339.30786,
      440.7,
      547.26786,
      662.22786
    ],
    "checkboxY": 439.68,
    "rationale": {
      "x": 77.76,
      "y": 402.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.3.1",
    "page": 211,
    "pageHeight": 612,
    "checkboxes": [
      131.34786,
      237.18786,
      341.34786,
      443.34,
      549.54786,
      662.82786
    ],
    "checkboxY": 334.32,
    "rationale": {
      "x": 83.04,
      "y": 297.68,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.3.1.1",
    "page": 212,
    "pageHeight": 612,
    "checkboxes": [
      129.18786,
      238.74786,
      340.98786,
      441.3,
      548.34786,
      662.46786
    ],
    "checkboxY": 323.52,
    "rationale": {
      "x": 77.76,
      "y": 286.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.3.2",
    "page": 214,
    "pageHeight": 612,
    "checkboxes": [
      127.26786,
      235.02786,
      339.30786,
      440.58,
      547.26786,
      661.9878600000001
    ],
    "checkboxY": 384,
    "rationale": {
      "x": 77.76,
      "y": 347.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.3.3",
    "page": 216,
    "pageHeight": 612,
    "checkboxes": [
      131.82786,
      238.74786,
      340.98786,
      441.3,
      548.34786,
      662.46786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 83.04,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.3.4",
    "page": 217,
    "pageHeight": 612,
    "checkboxes": [
      129.18786,
      238.74786,
      340.98786,
      441.3,
      548.34786,
      662.46786
    ],
    "checkboxY": 384,
    "rationale": {
      "x": 77.76,
      "y": 347.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.4.1",
    "page": 219,
    "pageHeight": 612,
    "checkboxes": [
      127.26786,
      234.90786,
      339.18786,
      440.58,
      547.26786,
      661.9878600000001
    ],
    "checkboxY": 396.96,
    "rationale": {
      "x": 77.76,
      "y": 360.32,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.4.1.1",
    "page": 220,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.22786,
      441.53999999999996,
      548.58786,
      662.46786
    ],
    "checkboxY": 436.92,
    "rationale": {
      "x": 77.76,
      "y": 400.28,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.4.1.2",
    "page": 221,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.22786,
      441.53999999999996,
      548.58786,
      662.46786
    ],
    "checkboxY": 440.64,
    "rationale": {
      "x": 77.76,
      "y": 403.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.4.2",
    "page": 222,
    "pageHeight": 612,
    "checkboxes": [
      131.94786,
      238.98785999999998,
      341.22786,
      441.53999999999996,
      548.70786,
      662.46786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 83.04,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.4.3",
    "page": 223,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.98785999999998,
      341.22786,
      441.53999999999996,
      548.70786,
      662.46786
    ],
    "checkboxY": 399,
    "rationale": {
      "x": 77.76,
      "y": 362.24,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.4.4",
    "page": 224,
    "pageHeight": 612,
    "checkboxes": [
      132.06786,
      238.98785999999998,
      341.22786,
      441.53999999999996,
      548.58786,
      662.46786
    ],
    "checkboxY": 420.24,
    "rationale": {
      "x": 83.16,
      "y": 383.48,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.4.5",
    "page": 225,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.22786,
      441.53999999999996,
      548.58786,
      662.46786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.4.5.1",
    "page": 226,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.86785999999998,
      341.10786,
      441.42,
      548.46786,
      662.46786
    ],
    "checkboxY": 440.64,
    "rationale": {
      "x": 77.76,
      "y": 403.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.4.6",
    "page": 227,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.86785999999998,
      341.10786,
      441.42,
      548.46786,
      662.46786
    ],
    "checkboxY": 412.44,
    "rationale": {
      "x": 77.76,
      "y": 375.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.4.7",
    "page": 229,
    "pageHeight": 612,
    "checkboxes": [
      127.26786,
      235.14785999999998,
      339.42786,
      440.7,
      547.14786,
      661.8678600000001
    ],
    "checkboxY": 412.08,
    "rationale": {
      "x": 77.76,
      "y": 375.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.5.1",
    "page": 230,
    "pageHeight": 612,
    "checkboxes": [
      127.26786,
      235.14785999999998,
      339.30786,
      440.46,
      547.14786,
      661.9878600000001
    ],
    "checkboxY": 343.68,
    "rationale": {
      "x": 77.76,
      "y": 306.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.5.1.1",
    "page": 231,
    "pageHeight": 612,
    "checkboxes": [
      127.38786,
      235.14785999999998,
      339.42786,
      440.58,
      547.26786,
      661.8678600000001
    ],
    "checkboxY": 397.2,
    "rationale": {
      "x": 77.76,
      "y": 360.56,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.5.1.2",
    "page": 232,
    "pageHeight": 612,
    "checkboxes": [
      127.38786,
      235.14785999999998,
      339.42786,
      440.58,
      547.26786,
      661.8678600000001
    ],
    "checkboxY": 434.28,
    "rationale": {
      "x": 77.76,
      "y": 397.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.5.1.2.1",
    "page": 233,
    "pageHeight": 612,
    "checkboxes": [
      132.06786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.46786
    ],
    "checkboxY": 415.2,
    "rationale": {
      "x": 83.16,
      "y": 378.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "9.5.1.3",
    "page": 234,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.46786
    ],
    "checkboxY": 372.96,
    "rationale": {
      "x": 77.76,
      "y": 336.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.1.1",
    "page": 235,
    "pageHeight": 612,
    "checkboxes": [
      134.10786,
      242.82786,
      342.90786,
      442.14,
      549.54786,
      662.82786
    ],
    "checkboxY": 279.36,
    "rationale": {
      "x": 83.04,
      "y": 242.72000000000003,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.1.2",
    "page": 236,
    "pageHeight": 612,
    "checkboxes": [
      131.46786,
      242.82786,
      342.90786,
      442.14,
      549.54786,
      662.82786
    ],
    "checkboxY": 440.04,
    "rationale": {
      "x": 77.76,
      "y": 403.4,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.2.1",
    "page": 237,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 390.72,
    "rationale": {
      "x": 77.76,
      "y": 353.96,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.2.1.1",
    "page": 238,
    "pageHeight": 612,
    "checkboxes": [
      131.46786,
      242.82786,
      342.90786,
      442.14,
      549.54786,
      662.82786
    ],
    "checkboxY": 435.6,
    "rationale": {
      "x": 77.76,
      "y": 398.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.2.1.2",
    "page": 239,
    "pageHeight": 612,
    "checkboxes": [
      131.46786,
      242.82786,
      342.90786,
      442.14,
      549.54786,
      662.82786
    ],
    "checkboxY": 435.6,
    "rationale": {
      "x": 77.76,
      "y": 398.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.2.1.3",
    "page": 240,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 435.12,
    "rationale": {
      "x": 77.76,
      "y": 398.48,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.2.1.4",
    "page": 241,
    "pageHeight": 612,
    "checkboxes": [
      132.18786,
      244.38786,
      346.5,
      446.82,
      553.7478600000001,
      665.1078600000001
    ],
    "checkboxY": 440.64,
    "rationale": {
      "x": 77.76,
      "y": 403.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.2.1.5",
    "page": 242,
    "pageHeight": 612,
    "checkboxes": [
      132.18786,
      244.38786,
      346.50786,
      446.82,
      553.7478600000001,
      665.1078600000001
    ],
    "checkboxY": 398.4,
    "rationale": {
      "x": 77.76,
      "y": 361.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.2.1.6",
    "page": 243,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 412.44,
    "rationale": {
      "x": 77.76,
      "y": 375.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.2.1.7",
    "page": 244,
    "pageHeight": 612,
    "checkboxes": [
      131.46786,
      242.82786,
      344.10786,
      443.34,
      549.42786,
      662.82786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.2.2",
    "page": 245,
    "pageHeight": 612,
    "checkboxes": [
      134.22786,
      242.82786,
      344.10786,
      443.34,
      549.42786,
      662.82786
    ],
    "checkboxY": 355.8,
    "rationale": {
      "x": 83.16,
      "y": 319.16,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.3.1",
    "page": 246,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 393.36,
    "rationale": {
      "x": 77.76,
      "y": 356.6,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.3.2",
    "page": 247,
    "pageHeight": 612,
    "checkboxes": [
      129.54786,
      239.10786,
      341.34786,
      441.53999999999996,
      548.22786,
      662.34786
    ],
    "checkboxY": 437.4,
    "rationale": {
      "x": 77.76,
      "y": 400.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.3.3",
    "page": 248,
    "pageHeight": 612,
    "checkboxes": [
      134.82786,
      249.78786,
      346.86786,
      446.94,
      559.14786,
      667.7478600000001
    ],
    "checkboxY": 417.36,
    "rationale": {
      "x": 77.76,
      "y": 380.72,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.3.4",
    "page": 249,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 429.48,
    "rationale": {
      "x": 77.76,
      "y": 392.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.4.1",
    "page": 250,
    "pageHeight": 612,
    "checkboxes": [
      128.82786,
      237.42785999999998,
      340.14786000000004,
      439.5,
      544.26786,
      660.18786
    ],
    "checkboxY": 323.52,
    "rationale": {
      "x": 77.76,
      "y": 286.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.4.1.1",
    "page": 251,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      340.98786,
      441.18,
      548.22786,
      662.34786
    ],
    "checkboxY": 308.28,
    "rationale": {
      "x": 77.76,
      "y": 271.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.4.2",
    "page": 252,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.10786,
      441.3,
      548.22786,
      662.34786
    ],
    "checkboxY": 437.88,
    "rationale": {
      "x": 77.76,
      "y": 401.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.4.2.1",
    "page": 253,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.10786,
      441.3,
      548.22786,
      662.34786
    ],
    "checkboxY": 415.2,
    "rationale": {
      "x": 77.76,
      "y": 378.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.4.3",
    "page": 254,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 418.8,
    "rationale": {
      "x": 77.76,
      "y": 382.04,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.5.1",
    "page": 255,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.22786,
      662.34786
    ],
    "checkboxY": 390.96,
    "rationale": {
      "x": 77.76,
      "y": 354.32,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.6.1",
    "page": 257,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 389.52,
    "rationale": {
      "x": 77.76,
      "y": 352.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.6.2",
    "page": 258,
    "pageHeight": 612,
    "checkboxes": [
      128.70786,
      237.30785999999998,
      340.14786000000004,
      439.5,
      544.26786,
      660.18786
    ],
    "checkboxY": 355.8,
    "rationale": {
      "x": 77.76,
      "y": 319.16,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.6.3",
    "page": 259,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 412.44,
    "rationale": {
      "x": 77.76,
      "y": 375.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.7.1",
    "page": 260,
    "pageHeight": 612,
    "checkboxes": [
      129.42,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 259.56,
    "rationale": {
      "x": 77.76,
      "y": 222.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.7.2",
    "page": 262,
    "pageHeight": 612,
    "checkboxes": [
      128.82786,
      237.42785999999998,
      340.14786000000004,
      439.5,
      544.26786,
      660.18786
    ],
    "checkboxY": 252.24,
    "rationale": {
      "x": 77.76,
      "y": 215.48,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "10.7.3",
    "page": 264,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 314.4,
    "rationale": {
      "x": 77.76,
      "y": 277.76,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.1.1",
    "page": 266,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 317.28,
    "rationale": {
      "x": 77.76,
      "y": 280.52,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.1.2",
    "page": 267,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 440.64,
    "rationale": {
      "x": 77.76,
      "y": 403.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.2.1",
    "page": 268,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 340.68,
    "rationale": {
      "x": 77.76,
      "y": 303.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.2.2",
    "page": 270,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.3.1",
    "page": 271,
    "pageHeight": 612,
    "checkboxes": [
      128.70786,
      237.18786,
      340.14786000000004,
      439.38,
      544.14786,
      660.30786
    ],
    "checkboxY": 326.52,
    "rationale": {
      "x": 77.76,
      "y": 289.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.3.1.1",
    "page": 273,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.86785999999998,
      340.98786,
      441.18,
      548.22786,
      662.46786
    ],
    "checkboxY": 387,
    "rationale": {
      "x": 77.76,
      "y": 350.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.3.1.2",
    "page": 274,
    "pageHeight": 612,
    "checkboxes": [
      131.58786,
      242.94786,
      342.90786,
      442.02,
      549.66786,
      662.94786
    ],
    "checkboxY": 175.68,
    "rationale": {
      "x": 77.76,
      "y": 138.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.3.1.3",
    "page": 276,
    "pageHeight": 612,
    "checkboxes": [
      128.82786,
      237.42785999999998,
      340.26786000000004,
      442.26,
      549.66786,
      662.94786
    ],
    "checkboxY": 393.48,
    "rationale": {
      "x": 77.76,
      "y": 356.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.3.2",
    "page": 278,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.86785999999998,
      341.22786,
      441.42,
      548.1078600000001
    ],
    "checkboxY": 384,
    "rationale": {
      "x": 77.76,
      "y": 347.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.3.2.1",
    "page": 279,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      339.18786,
      439.26,
      548.34786,
      662.46786
    ],
    "checkboxY": 377.64,
    "rationale": {
      "x": 77.76,
      "y": 341,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.4.1",
    "page": 281,
    "pageHeight": 612,
    "checkboxes": [
      128.70786,
      237.30785999999998,
      340.38786000000005,
      439.62,
      544.14786,
      660.18786
    ],
    "checkboxY": 275.16,
    "rationale": {
      "x": 77.76,
      "y": 238.52,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.4.2",
    "page": 282,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.86785999999998,
      341.22786,
      441.42,
      548.22786,
      662.34786
    ],
    "checkboxY": 371.88,
    "rationale": {
      "x": 77.76,
      "y": 335.24,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.4.3",
    "page": 283,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 251.04,
    "rationale": {
      "x": 77.76,
      "y": 214.4,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.4.4",
    "page": 285,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 412.44,
    "rationale": {
      "x": 77.76,
      "y": 375.8,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.4.5",
    "page": 286,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.22786,
      662.34786
    ],
    "checkboxY": 344.04,
    "rationale": {
      "x": 77.76,
      "y": 307.28,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.4.6",
    "page": 287,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 222.96,
    "rationale": {
      "x": 77.76,
      "y": 186.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.4.7",
    "page": 289,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 415.2,
    "rationale": {
      "x": 77.76,
      "y": 378.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.5.1",
    "page": 290,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      340.98786,
      441.18,
      548.22786,
      662.34786
    ],
    "checkboxY": 340.68,
    "rationale": {
      "x": 77.76,
      "y": 303.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.5.1.1",
    "page": 291,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.21999999999997,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 179.76,
    "rationale": {
      "x": 77.76,
      "y": 143.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.5.2",
    "page": 293,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 412.2,
    "rationale": {
      "x": 77.76,
      "y": 375.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "11.6.1",
    "page": 294,
    "pageHeight": 612,
    "checkboxes": [
      128.82786,
      237.42785999999998,
      340.14786000000004,
      439.38,
      544.14786,
      660.18786
    ],
    "checkboxY": 270,
    "rationale": {
      "x": 77.76,
      "y": 233.24,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.1.1",
    "page": 296,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.22786,
      662.46786
    ],
    "checkboxY": 273.12,
    "rationale": {
      "x": 77.76,
      "y": 236.48,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.1.2",
    "page": 297,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.22786,
      662.46786
    ],
    "checkboxY": 412.08,
    "rationale": {
      "x": 77.76,
      "y": 375.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.1.3",
    "page": 298,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.46786
    ],
    "checkboxY": 429.48,
    "rationale": {
      "x": 77.64,
      "y": 392.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.1.4",
    "page": 299,
    "pageHeight": 612,
    "checkboxes": [
      129.30786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.46786
    ],
    "checkboxY": 429.12,
    "rationale": {
      "x": 77.64,
      "y": 392.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.2.1",
    "page": 300,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 351.6,
    "rationale": {
      "x": 77.76,
      "y": 314.96,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.3.1",
    "page": 301,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.10786,
      441.3,
      548.22786,
      662.34786
    ],
    "checkboxY": 284.88,
    "rationale": {
      "x": 77.76,
      "y": 248.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.3.2",
    "page": 302,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.10786,
      441.3,
      548.22
    ],
    "checkboxY": 391.2,
    "rationale": {
      "x": 77.76,
      "y": 354.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.3.3",
    "page": 303,
    "pageHeight": 612,
    "checkboxes": [
      128.82786,
      237.42785999999998,
      340.38786000000005,
      439.62,
      544.14786,
      660.18786
    ],
    "checkboxY": 384,
    "rationale": {
      "x": 77.76,
      "y": 347.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.3.4",
    "page": 304,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.22786,
      441.42,
      548.22786,
      662.34786
    ],
    "checkboxY": 347.76,
    "rationale": {
      "x": 77.76,
      "y": 311.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.4.1",
    "page": 305,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 347.4,
    "rationale": {
      "x": 77.76,
      "y": 310.76,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.4.2",
    "page": 306,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.10786,
      441.3,
      548.22786,
      662.34786
    ],
    "checkboxY": 348,
    "rationale": {
      "x": 77.76,
      "y": 311.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.4.2.1",
    "page": 308,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.10786,
      441.3,
      548.22786,
      662.34786
    ],
    "checkboxY": 398.16,
    "rationale": {
      "x": 77.76,
      "y": 361.4,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.5.1",
    "page": 309,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 396.96,
    "rationale": {
      "x": 77.76,
      "y": 360.32,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.5.2",
    "page": 310,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 286.56,
    "rationale": {
      "x": 77.76,
      "y": 249.92000000000002,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.5.2.1",
    "page": 311,
    "pageHeight": 612,
    "checkboxes": [
      129.42,
      238.98785999999998,
      341.10786,
      441.3,
      548.34,
      662.34786
    ],
    "checkboxY": 321.12,
    "rationale": {
      "x": 77.76,
      "y": 283.76,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.5.3",
    "page": 312,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 318.48,
    "rationale": {
      "x": 77.76,
      "y": 281.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.6.1",
    "page": 314,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 385.92,
    "rationale": {
      "x": 77.76,
      "y": 349.16,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.6.2",
    "page": 315,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 387,
    "rationale": {
      "x": 77.76,
      "y": 350.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.6.3",
    "page": 316,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 398.16,
    "rationale": {
      "x": 77.76,
      "y": 361.4,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.6.3.1",
    "page": 317,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 247.8,
    "rationale": {
      "x": 77.76,
      "y": 211.04,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.6.3.2",
    "page": 318,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.09999999999997,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 318.72,
    "rationale": {
      "x": 77.76,
      "y": 281.6,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.7.1",
    "page": 319,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.09999999999997,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 385.68,
    "rationale": {
      "x": 77.76,
      "y": 348.56,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.8.1",
    "page": 320,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 379.56,
    "rationale": {
      "x": 77.76,
      "y": 342.92,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.8.2",
    "page": 321,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 390,
    "rationale": {
      "x": 77.76,
      "y": 353.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.8.3",
    "page": 322,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 440.4,
    "rationale": {
      "x": 77.76,
      "y": 403.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.8.4",
    "page": 323,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 433.8,
    "rationale": {
      "x": 77.76,
      "y": 397.04,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.8.5",
    "page": 324,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 429.24,
    "rationale": {
      "x": 77.76,
      "y": 392.6,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.9.1",
    "page": 325,
    "pageHeight": 612,
    "checkboxes": [
      129.54786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 374.76,
    "rationale": {
      "x": 77.76,
      "y": 338.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.9.2",
    "page": 326,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.34786,
      662.34786
    ],
    "checkboxY": 372.96,
    "rationale": {
      "x": 77.76,
      "y": 336.2,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.10.1",
    "page": 327,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      238.98785999999998,
      341.10786,
      441.3,
      548.22786,
      662.34786
    ],
    "checkboxY": 273.12,
    "rationale": {
      "x": 77.76,
      "y": 236.48,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.10.2",
    "page": 328,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 284.28,
    "rationale": {
      "x": 77.76,
      "y": 247.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.10.3",
    "page": 329,
    "pageHeight": 612,
    "checkboxes": [
      129.42786,
      239.10786,
      341.22786,
      441.42,
      548.34786,
      662.34786
    ],
    "checkboxY": 287.16,
    "rationale": {
      "x": 77.76,
      "y": 250.51999999999998,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.10.4",
    "page": 330,
    "pageHeight": 612,
    "checkboxes": [
      128.82786,
      237.42785999999998,
      340.38786000000005,
      439.62,
      544.14786,
      660.18786
    ],
    "checkboxY": 407.76,
    "rationale": {
      "x": 77.76,
      "y": 371.12,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.10.4.1",
    "page": 331,
    "pageHeight": 612,
    "checkboxes": [
      128.82786,
      237.42785999999998,
      340.14786000000004,
      439.38,
      544.14786,
      660.18786
    ],
    "checkboxY": 415.2,
    "rationale": {
      "x": 77.76,
      "y": 378.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.10.5",
    "page": 332,
    "pageHeight": 612,
    "checkboxes": [
      128.82786,
      237.42785999999998,
      340.14786000000004,
      439.38,
      544.14786,
      660.18786
    ],
    "checkboxY": 358.8,
    "rationale": {
      "x": 77.76,
      "y": 322.16,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.10.6",
    "page": 333,
    "pageHeight": 612,
    "checkboxes": [
      128.82786,
      237.42785999999998,
      340.38786000000005,
      439.62,
      544.14786,
      660.18786
    ],
    "checkboxY": 437.4,
    "rationale": {
      "x": 77.76,
      "y": 400.64,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "12.10.7",
    "page": 334,
    "pageHeight": 612,
    "checkboxes": [
      128.70786,
      237.29999999999998,
      340.02786000000003,
      439.38,
      544.14786,
      660.18786
    ],
    "checkboxY": 357.96,
    "rationale": {
      "x": 77.76,
      "y": 321.32,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "A1.1.1",
    "page": 336,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.94786,
      449.82786000000004,
      557.82786,
      665.70786
    ],
    "checkboxY": 286.8,
    "rationale": {
      "x": 77.76,
      "y": 250.04000000000002,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "A1.1.2",
    "page": 337,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      343.02786000000003,
      450.90786,
      557.82786,
      665.70786
    ],
    "checkboxY": 233.64,
    "rationale": {
      "x": 77.76,
      "y": 196.88,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "A1.1.3",
    "page": 338,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      341.82786000000004,
      449.82786000000004,
      557.82786,
      665.70786
    ],
    "checkboxY": 261.48,
    "rationale": {
      "x": 77.76,
      "y": 224.84,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "A1.1.4",
    "page": 339,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      343.02786000000003,
      450.90786,
      557.82786,
      665.70786
    ],
    "checkboxY": 410.16,
    "rationale": {
      "x": 77.76,
      "y": 373.52,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "A1.2.1",
    "page": 340,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      343.02786000000003,
      450.90786,
      557.82786,
      665.70786
    ],
    "checkboxY": 328.2,
    "rationale": {
      "x": 77.76,
      "y": 291.44,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "A1.2.2",
    "page": 341,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      344.22786,
      451.98786,
      557.70786,
      665.58786
    ],
    "checkboxY": 429,
    "rationale": {
      "x": 77.76,
      "y": 392.36,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "A1.2.3",
    "page": 342,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      344.22786,
      451.98786,
      557.70786,
      665.58786
    ],
    "checkboxY": 399.72,
    "rationale": {
      "x": 77.76,
      "y": 363.08,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "A2.1.1",
    "page": 343,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      344.22786,
      451.98786,
      557.70786
    ],
    "checkboxY": 338.88,
    "rationale": {
      "x": 77.76,
      "y": 300.56,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "A2.1.2",
    "page": 344,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.82786,
      344.22786,
      451.98786,
      557.70786
    ],
    "checkboxY": 349.44,
    "rationale": {
      "x": 77.76,
      "y": 312.68,
      "maxWidth": 500,
      "maxLines": 8
    }
  },
  {
    "requirementRef": "A2.1.3",
    "page": 345,
    "pageHeight": 612,
    "checkboxes": [
      125.94786,
      233.94786,
      344.22786,
      452.09999999999997,
      557.8199999999999
    ],
    "checkboxY": 441.96,
    "rationale": {
      "x": 77.76,
      "y": 405.32,
      "maxWidth": 500,
      "maxLines": 8
    }
  }
];
